import type { AnalysisReport } from "./schema"
import type { ProjectInsights } from "./project-insights"
import { computeUnifiedHealth, type UnifiedHealth } from "./health"

/** Build a shareable Markdown report from the full analysis. */
export function buildMarkdownReport(report: AnalysisReport, insights: ProjectInsights): string {
  const health: UnifiedHealth = computeUnifiedHealth(report, insights)
  const { project } = report.meta
  const date = new Date(report.meta.finishedAt || Date.now()).toISOString().slice(0, 16).replace("T", " ")
  const lines: string[] = []

  lines.push(`# CodeLens Report`)
  lines.push("")
  lines.push(`**Project:** \`${project.root}\`  `)
  lines.push(`**Stack:** ${project.framework} · ${project.packageManager}  `)
  lines.push(`**Generated:** ${date} UTC  `)
  lines.push(`**Health:** ${health.score}/100 (Grade ${health.grade})`)
  lines.push("")

  lines.push(`## Health breakdown`)
  lines.push("")
  lines.push(`| Surface | Score | Weight | Issues |`)
  lines.push(`| --- | --: | --: | --: |`)
  for (const c of health.categories) {
    lines.push(`| ${c.label} | ${c.score} | ${Math.round(c.weight * 100)}% | ${c.issues} |`)
  }
  lines.push("")

  const sec = report.security
  const critical = sec.findings.filter((f) => f.severity === "critical").length
  const high = sec.findings.filter((f) => f.severity === "high").length

  lines.push(`## Summary`)
  lines.push("")
  lines.push(`- **Lint:** ${report.lint.errorCount} errors, ${report.lint.warningCount} warnings (${report.lint.fixableCount} auto-fixable)`)
  lines.push(`- **Types:** ${report.types.diagnostics.length} diagnostics`)
  lines.push(`- **Security:** ${sec.findings.length} findings (${critical} critical, ${high} high), ${sec.dependencies.length} vulnerable deps`)
  lines.push(`- **Dependencies:** ${report.deps.findings.length} findings across ${report.deps.counts.total} packages`)
  lines.push(`- **Database:** ${insights.database.findings.length} findings`)
  lines.push(`- **Accessibility:** score ${insights.accessibility.score}, ${insights.accessibility.violations.length} violations`)
  lines.push(`- **Performance:** score ${insights.performance.score}, ${insights.performance.findings.length} findings, ${insights.performance.totalBundleKb} KB first load`)
  lines.push(`- **Tests:** ${insights.tests.counts.passed}/${insights.tests.counts.total} passing, ${insights.tests.coverage.lines}% line coverage`)
  lines.push(`- **Environment:** ${insights.env.counts.issues} issues`)
  lines.push(`- **Network:** ${insights.network.counts.issues} issues across ${insights.network.counts.total} calls`)
  lines.push("")

  // Top security findings
  if (sec.findings.length) {
    lines.push(`## Security findings`)
    lines.push("")
    for (const f of [...sec.findings].sort((a, b) => rank(b.severity) - rank(a.severity)).slice(0, 15)) {
      lines.push(`- \`${f.severity.toUpperCase()}\` **${f.title}** — ${f.filePath}:${f.line}`)
    }
    lines.push("")
  }

  // Failing tests
  const failing = insights.tests.findings.filter((f) => f.kind === "failing")
  if (failing.length) {
    lines.push(`## Failing tests`)
    lines.push("")
    for (const f of failing) lines.push(`- **${f.title}** — ${f.filePath}:${f.line ?? 1}`)
    lines.push("")
  }

  // Accessibility violations
  if (insights.accessibility.violations.length) {
    lines.push(`## Accessibility violations`)
    lines.push("")
    for (const v of insights.accessibility.violations) {
      lines.push(`- \`${v.impact.toUpperCase()}\` **${v.rule}** (${v.principle}) — ${v.filePath}:${v.line}`)
    }
    lines.push("")
  }

  lines.push(`---`)
  lines.push(`_Generated by CodeLens._`)
  lines.push("")
  return lines.join("\n")
}

/** Build a structured JSON snapshot of the run. */
export function buildJsonReport(report: AnalysisReport, insights: ProjectInsights): string {
  const health = computeUnifiedHealth(report, insights)
  return JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      project: report.meta.project,
      health,
      report,
      insights,
    },
    null,
    2,
  )
}

function rank(s: string): number {
  return { critical: 6, error: 5, high: 4, warning: 3, medium: 3, low: 2, info: 1 }[s] ?? 1
}

/** Trigger a client-side file download for the given text content. */
export function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
